name: tf-ecs-automation
on:
  push:
    branches:
      - master

env:
  AWS_REGION: "ap-south-1"
  IMAGE_TAG: "latest"

permissions:        # this is required for aws role to work
  id-token: write
  contents: read

jobs:
  terraform:
    name: terraform
    runs-on: ubuntu-latest

    steps:
      - name: checkout                     # would be checkout to pull the code from the repo
        uses: actions/checkout@v2

      - name: configure aws credentials         # get the credentials from aws using assume role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::424736085230:role/Github
          role-session-name: Github
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: Login-ECR
        uses: aws-actions/Amazon-ECR-Login@v1

      - name: build, tag and push the docker image to amazon ecr
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.Login-ECR.outputs.registry}}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
      - name: apply terraform        # Apply the terraform code present in the repository
        run: terraform init && terraform apply --auto-approve
        working-directory: tfproject
        
